[global]
checkNewVersion = true
sendAnonymousUsage = false

[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.web]
    address = ":8088"

  [entryPoints.traefik]
    address = ":8444"


[providers]
  [providers.docker]
    watch = true
    exposedbydefault = false

[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
    addEntryPointsLabels = true
    addServicesLabels = true
    entryPoint = "metrics"

[ping]

[accessLog]
  filePath = "/var/log/traefik_access_original.log"
  bufferingSize = 100

[api]
